### ISSUE TITLE
code shows up in template

### ISSUE THREAD

**Issue by sapanparikh18** [sapanparikh18/Grails-3.1-AngularJS#1]
![screen shot 2016-01-23 at 11 07 19 am](https://cloud.githubusercontent.com/assets/1727880/12528601/86f44764-c1c1-11e5-8e39-543537043b20.png)
ng-route in the simplistic form ends up showing this line of code on the views

`angular.module('myapp.user').run(['$templateCache', function($templateCache) { $templateCache.put('/myapp/user/user.html', '`

For instance in the given screenshot it can be seen in one of the screen, surprisingly the template HTML is being compiled and injected correctly.

**Comment by sapanparikh18** [comment]
Thanks @craigburke this issue is fixed now, couldn't pin point the resolution to a file though

**Comment by craigburke** [comment]
@sapanparikh18 Cool! :+1: 

I'm not sure specifically what change fixed it, and I've never seen that particular issue. Very bizarre though.
